"""Add one-to-one relationship between Employee and User

Revision ID: 1a8263309d35
Revises: 7f1dc02814fe
Create Date: 2025-06-02 00:50:25.841051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a8263309d35'
down_revision = '7f1dc02814fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_employees_user_id', ['user_id'])
        batch_op.create_foreign_key('fk_employees_user_id_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint('fk_employees_user_id_users', type_='foreignkey')
        batch_op.drop_constraint('uq_employees_user_id', type_='unique')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
