"""Add company/user association and update company/user relationship

Revision ID: 670e4179b4bd
Revises: fe9cdd4a41be
Create Date: 2025-06-03 00:45:37.612908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '670e4179b4bd'
down_revision = 'fe9cdd4a41be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_users', schema=None) as batch_op:
        batch_op.alter_column('role_in_company',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('ADMIN', 'EDITOR', 'VIEWER', name='company_role_enum', native_enum=False),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_users', schema=None) as batch_op:
        batch_op.alter_column('role_in_company',
               existing_type=sa.Enum('ADMIN', 'EDITOR', 'VIEWER', name='company_role_enum', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
