"""Add RoleEnum and update user roles

Revision ID: fe9cdd4a41be
Revises: 49a532904e02
Create Date: 2025-06-02 18:48:12.099026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe9cdd4a41be'
down_revision = '49a532904e02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('SYSTEM_ADMIN', 'USER', name='role_enum', native_enum=False),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('SYSTEM_ADMIN', 'USER', name='role_enum', native_enum=False),
               type_=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
